// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(Request, Promise) {
    if (Promise == null) {
      Promise = require('bluebird');
    }
    Request.Request.prototype.endAsync = function() {
      return new Promise((function(_this) {
        return function(resolve, reject) {
          var error, error1;
          try {
            return _this.end(function(error, response) {
              if (error) {
                reject(error);
                return;
              }
              if (response.error) {
                reject(response.error);
                return;
              }
              return resolve(response);
            });
          } catch (error1) {
            error = error1;
            return reject(error);
          }
        };
      })(this));
    };
    Request.Request.prototype.then = function() {
      var ref;
      return (ref = this.endAsync()).then.apply(ref, arguments);
    };
    Request.Request.prototype["catch"] = function() {
      var ref;
      return (ref = this.endAsync())["catch"].apply(ref, arguments);
    };
    return Request;
  };

}).call(this);
