// Generated by CoffeeScript 1.8.0
(function() {
  var Promise, Request, _end;

  Request = require('superagent');

  Promise = require('bluebird');

  _end = Request.Request.prototype.end;

  Request.Request.prototype.end = function() {
    return new Promise((function(_this) {
      return function(resolve, reject) {
        var error;
        try {
          return _end.call(_this, function(error, response) {
            if (error) {
              reject(error);
              return;
            }
            if (response.error) {
              reject(response.error);
              return;
            }
            return resolve(response);
          });
        } catch (_error) {
          error = _error;
          return reject(error);
        }
      };
    })(this));
  };

  Request.Request.prototype.then = function() {
    var _ref;
    return (_ref = this.end()).then.apply(_ref, arguments);
  };

  Request.Request.prototype["catch"] = function() {
    var _ref;
    return (_ref = this.end())["catch"].apply(_ref, arguments);
  };

  module.exports = Request;

}).call(this);
